Repository RedcodesDev/KerenShemeshWeb, pull requests merged in 2022-05, with the labels that each got.

#7 Platzhalter entfernt
  index.html
Labels: enhancement, good first issue

#8 Fixed Issue #5: added link to GitHub repo
  index.html
Labels: feature

#11 Fix Icons not appearing in imprint
  imprint/index.html
  index.html
Labels: bug
